In [1]:
import numpy as np

In [4]:
arr=np.arange(8).reshape(4,2)


In [8]:
arr.shape

(4, 2)

In [9]:
arr.ndim

2

In [10]:
arr.itemsize

8

In [12]:
arr2=np.arange(100,200,10).reshape(5,2)
arr2

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [14]:
sampleArray=np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[51,54,57,60]])
sampleArray[...,2]

array([ 9, 21, 33, 57])

In [17]:
sampleArray=np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[51,54,57,60]])
row=sampleArray[1:len(sampleArray):2,...]
row

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [20]:
column=sampleArray[...,0:sampleArray.shape[1]:2]
column

array([[ 3,  9],
       [15, 21],
       [27, 33],
       [51, 57]])

In [22]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]]) 
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arrayOne*arrayOne

array([[ 25,  36,  81],
       [441, 324, 729]])

In [24]:
arrayTwo*arrayTwo

array([[ 225, 1089,  576],
       [  16,   49,    1]])

In [26]:
sp=np.arange(10,34).reshape(8,3)
np.split(sp,4)

[array([[10, 11, 12],
        [13, 14, 15]]), array([[16, 17, 18],
        [19, 20, 21]]), array([[22, 23, 24],
        [25, 26, 27]]), array([[28, 29, 30],
        [31, 32, 33]])]

In [29]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print(sampleArray.max(axis=0))
print(sampleArray.min(axis=1))

[82 94 73]
[34 12 53]


In [32]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
sampleArray[...,1]=newColumn
sampleArray


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [38]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1) 
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
a = np.array([1,2,3,2,3,4,3,4,5,6] )
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7]),)